//
// file:			export_symbols.h
// path:			include/winexetoservice/export_symbols.h
// created on:		2025 Sep 15
// created by:		Davit Kalantaryan (davit.kalantaryan@desy.de)
//

#ifndef WINEXETOSERVICE_INCLUDE_WINEXETOSERVICE_EXPORT_SYMBOLS_H
#define WINEXETOSERVICE_INCLUDE_WINEXETOSERVICE_EXPORT_SYMBOLS_H

#include <cinternal/internal_header.h>


#ifndef WINEXETOSERVICE_EXPORT
#if defined(WINEXETOSERVICE_COMPILING_SHARED_LIB)
#define WINEXETOSERVICE_EXPORT WINEXETOSERVICE_DLL_PUBLIC
#elif defined(WINEXETOSERVICE_USING_STATIC_LIB_OR_OBJECTS)
#define WINEXETOSERVICE_EXPORT
#elif defined(WINEXETOSERVICE_LOAD_FROM_DLL)
#define WINEXETOSERVICE_EXPORT WINEXETOSERVICE_IMPORT_FROM_DLL
#else
#define WINEXETOSERVICE_EXPORT WINEXETOSERVICE_DLL_PRIVATE
#endif
#endif


#endif  // #ifndef WINEXETOSERVICE_INCLUDE_WINEXETOSERVICE_EXPORT_SYMBOLS_H
